[package]
name = "grrs"
version = "0.1.0"
authors = ["Stefan Papp <stefan.papp@data-wizard.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
